#!/usr/bin/env python3
"""
RC Plan Management System
Handles plan generation, storage, and execution for action-type requests.
"""

import os
import json
import time
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List, Optional
from dataclasses import dataclass


@dataclass
class Plan:
    """Represents a generated plan"""
    id: str
    title: str
    description: str
    steps: List[Dict[str, Any]]
    context: Dict[str, Any]
    created_at: str
    status: str = "pending"  # pending, active, completed, cancelled
    estimated_time: str = "unknown"
    required_agents: List[str] = None
    
    def __post_init__(self):
        if self.required_agents is None:
            self.required_agents = []


class PlanManager:
    """Manages plan generation, storage, and execution"""
    
    def __init__(self):
        self.plans_dir = Path('plans')
        self._ensure_plans_structure()
        
    def _ensure_plans_structure(self):
        """Ensure plans directory structure exists"""
        directories = [
            self.plans_dir,
            self.plans_dir / 'active',
            self.plans_dir / 'completed',
            self.plans_dir / 'templates',
            self.plans_dir / 'archive'
        ]
        
        for directory in directories:
            directory.mkdir(exist_ok=True)
            
        # Create README if it doesn't exist
        readme_path = self.plans_dir / 'README.md'
        if not readme_path.exists():
            readme_content = """# RSC03 Plans Directory

This directory contains plans generated by the RC command for action-type requests.

## Structure:
- `active/` - Currently active plans being worked on
- `completed/` - Successfully completed plans
- `templates/` - Plan templates for common tasks
- `archive/` - Archived plans for reference

## Plan Files:
Each plan is stored as a JSON file with metadata and a markdown file with the human-readable plan.

## Usage:
- Plans are generated with `rc -plan "your request"`
- Plans can be executed with team interaction in interactive chat
- Use `rc chat` and reference plan files for team collaboration
"""
            readme_path.write_text(readme_content)
    
    def generate_plan(self, request: str, context: Dict[str, Any]) -> str:
        """Generate a plan for the given request using context"""
        
        # Analyze request to determine plan type and complexity
        plan_analysis = self._analyze_request(request, context)
        
        # Generate plan based on analysis
        plan_content = self._create_plan_content(request, context, plan_analysis)
        
        return plan_content
    
    def _analyze_request(self, request: str, context: Dict[str, Any]) -> Dict[str, Any]:
        """Analyze request to determine planning approach"""
        request_lower = request.lower()
        
        # Determine plan complexity
        complexity_indicators = {
            'simple': ['fix', 'debug', 'analyze', 'explain', 'review'],
            'medium': ['build', 'create', 'develop', 'implement', 'design'],
            'complex': ['system', 'architecture', 'full-stack', 'enterprise', 'scalable']
        }
        
        complexity = 'simple'
        for level, indicators in complexity_indicators.items():
            if any(indicator in request_lower for indicator in indicators):
                complexity = level
        
        # Determine required agents based on request content
        agent_mapping = {
            'research': ['research', 'analyze', 'investigate', 'study', 'gather'],
            'architect': ['design', 'architecture', 'structure', 'plan', 'system'],
            'implementer': ['build', 'code', 'develop', 'implement', 'create'],
            'qa': ['test', 'quality', 'validate', 'verify', 'check'],
            'security': ['security', 'secure', 'auth', 'permission', 'vulnerability'],
            'infrastructure': ['deploy', 'server', 'cloud', 'infrastructure', 'devops'],
            'writer': ['document', 'readme', 'guide', 'manual', 'documentation']
        }
        
        required_agents = ['orchestrator']  # Always include orchestrator
        for agent, keywords in agent_mapping.items():
            if any(keyword in request_lower for keyword in keywords):
                required_agents.append(agent)
        
        # Estimate time based on complexity and agents
        time_estimates = {
            'simple': '30 minutes - 2 hours',
            'medium': '2 hours - 1 day',
            'complex': '1 day - 1 week'
        }
        
        return {
            'complexity': complexity,
            'required_agents': required_agents,
            'estimated_time': time_estimates[complexity],
            'project_type': context.get('project_type', 'unknown'),
            'has_existing_code': len(context.get('files_present', [])) > 0
        }
    
    def _create_plan_content(self, request: str, context: Dict[str, Any], analysis: Dict[str, Any]) -> str:
        """Create the actual plan content"""
        
        plan_template = f"""# Plan: {request}

## Overview
**Request**: {request}
**Complexity**: {analysis['complexity'].title()}
**Estimated Time**: {analysis['estimated_time']}
**Project Type**: {analysis['project_type'].title()}

## Context Analysis
- **Current Directory**: {context['current_dir']}
- **Project Type**: {context['project_type']}
- **RSC03 Relation**: {context['rsc03_relation']}
- **Existing Files**: {len(context.get('files_present', []))} files detected
- **Git Status**: {context.get('git_info', {}).get('status', 'unknown')}

## Required Agents
{self._format_agent_list(analysis['required_agents'])}

## Execution Plan

### Phase 1: Analysis & Planning
**Agent**: Project Orchestrator
**Tasks**:
- Analyze the request in detail
- Confirm requirements and scope
- Coordinate with other agents as needed
- Set up project structure if required

### Phase 2: Implementation Steps
{self._generate_implementation_steps(request, context, analysis)}

### Phase 3: Quality Assurance
**Agent**: Quality Assurance
**Tasks**:
- Review implementation against requirements
- Test functionality and edge cases
- Validate security considerations
- Ensure code quality standards

### Phase 4: Documentation & Completion
**Agent**: Technical Writer
**Tasks**:
- Document the solution
- Create usage instructions
- Update project README if needed
- Archive plan as completed

## Success Criteria
{self._generate_success_criteria(request, analysis)}

## Risk Assessment
{self._generate_risk_assessment(analysis)}

## Next Steps
1. Review this plan with the user
2. Get approval to proceed
3. Execute plan with multi-agent coordination
4. Monitor progress and adjust as needed

---
*Generated by RSC03 RC Command at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""
        return plan_template
    
    def _format_agent_list(self, agents: List[str]) -> str:
        """Format the list of required agents"""
        agent_descriptions = {
            'orchestrator': 'Project Orchestrator - Overall coordination and management',
            'research': 'Research Analyst - Information gathering and analysis',
            'architect': 'Solution Architect - System design and architecture',
            'implementer': 'Code Implementer - Development and coding',
            'qa': 'Quality Assurance - Testing and validation',
            'security': 'Security Specialist - Security review and implementation',
            'infrastructure': 'Infrastructure Specialist - Deployment and DevOps',
            'writer': 'Technical Writer - Documentation and guides'
        }
        
        formatted = []
        for agent in agents:
            description = agent_descriptions.get(agent, f'{agent.title()} - Specialized agent')
            formatted.append(f"- **{agent.title()}**: {description}")
        
        return '\n'.join(formatted)
    
    def _generate_implementation_steps(self, request: str, context: Dict[str, Any], analysis: Dict[str, Any]) -> str:
        """Generate implementation steps based on request analysis"""
        
        if 'build' in request.lower() or 'create' in request.lower():
            return """**Agent**: Solution Architect + Code Implementer
**Tasks**:
- Design system architecture
- Set up project structure
- Implement core functionality
- Integrate with existing codebase if applicable
- Handle error cases and edge conditions"""
        
        elif 'analyze' in request.lower() or 'review' in request.lower():
            return """**Agent**: Research Analyst
**Tasks**:
- Examine existing code and documentation
- Identify patterns and issues
- Generate comprehensive analysis report
- Provide recommendations for improvements
- Document findings clearly"""
        
        elif 'fix' in request.lower() or 'debug' in request.lower():
            return """**Agent**: Code Implementer + Quality Assurance
**Tasks**:
- Reproduce and isolate the issue
- Analyze root cause
- Implement fix with minimal impact
- Test fix thoroughly
- Ensure no regression issues"""
        
        else:
            return """**Agent**: Multiple agents as determined by orchestrator
**Tasks**:
- Break down request into actionable tasks
- Assign tasks to appropriate specialized agents
- Coordinate execution across agents
- Ensure quality and consistency
- Integrate results into cohesive solution"""
    
    def _generate_success_criteria(self, request: str, analysis: Dict[str, Any]) -> str:
        """Generate success criteria for the plan"""
        criteria = [
            "✅ Request requirements fully understood and addressed",
            "✅ Solution implemented according to best practices",
            "✅ Code quality meets RSC03 standards",
            "✅ All tests pass and functionality verified"
        ]
        
        if analysis['complexity'] in ['medium', 'complex']:
            criteria.append("✅ Documentation updated and comprehensive")
            criteria.append("✅ Security considerations addressed")
        
        if analysis['has_existing_code']:
            criteria.append("✅ Integration with existing codebase seamless")
            criteria.append("✅ No breaking changes to existing functionality")
        
        return '\n'.join(criteria)
    
    def _generate_risk_assessment(self, analysis: Dict[str, Any]) -> str:
        """Generate risk assessment for the plan"""
        risks = []
        
        if analysis['complexity'] == 'complex':
            risks.append("🔶 **High Complexity**: May require multiple iterations and refinements")
        
        if len(analysis['required_agents']) > 4:
            risks.append("🔶 **Multi-Agent Coordination**: Complex coordination may introduce delays")
        
        if analysis['has_existing_code']:
            risks.append("🔶 **Integration Risk**: Changes may affect existing functionality")
        
        if not risks:
            risks.append("🟢 **Low Risk**: Straightforward implementation with minimal dependencies")
        
        return '\n'.join(risks)
    
    def save_plan(self, plan_content: str, request: str) -> str:
        """Save plan to active plans directory"""
        
        # Generate plan ID and filename
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        plan_id = f"plan_{timestamp}"
        
        # Create safe filename from request
        safe_title = ''.join(c for c in request[:50] if c.isalnum() or c in (' ', '-', '_')).strip()
        safe_title = safe_title.replace(' ', '_')
        
        filename = f"{plan_id}_{safe_title}.md"
        plan_path = self.plans_dir / 'active' / filename
        
        # Save plan content
        plan_path.write_text(plan_content)
        
        # Create metadata file
        metadata = {
            'id': plan_id,
            'title': request,
            'filename': filename,
            'created_at': datetime.now().isoformat(),
            'status': 'pending',
            'path': str(plan_path)
        }
        
        metadata_path = self.plans_dir / 'active' / f"{plan_id}_metadata.json"
        metadata_path.write_text(json.dumps(metadata, indent=2))
        
        return str(plan_path)
    
    def execute_plan(self, plan_path: str, context: Dict[str, Any], verbose: bool = False, debug: bool = False):
        """Execute a plan with multi-agent coordination"""
        
        if verbose or debug:
            print(f"🚀 Executing plan: {plan_path}")
            print(f"📍 Context: {context['current_dir']}")
        
        # For now, this is a placeholder for plan execution
        # In the full implementation, this would:
        # 1. Parse the plan file
        # 2. Initialize the required agents
        # 3. Execute each phase with appropriate agents
        # 4. Coordinate between agents
        # 5. Monitor progress and handle errors
        
        print("📋 Plan execution initiated...")
        print("🤖 This feature will coordinate with the RSC03 multi-agent system")
        print("💬 For now, use 'rc chat' and reference the plan file for team interaction")
        
        # Move plan to active status
        self._update_plan_status(plan_path, 'active')
    
    def _update_plan_status(self, plan_path: str, status: str):
        """Update plan status in metadata"""
        plan_path_obj = Path(plan_path)
        plan_id = plan_path_obj.stem.split('_')[0] + '_' + plan_path_obj.stem.split('_')[1]
        metadata_path = plan_path_obj.parent / f"{plan_id}_metadata.json"
        
        if metadata_path.exists():
            try:
                metadata = json.loads(metadata_path.read_text())
                metadata['status'] = status
                metadata['updated_at'] = datetime.now().isoformat()
                metadata_path.write_text(json.dumps(metadata, indent=2))
            except (json.JSONDecodeError, KeyError):
                pass
    
    def list_plans(self, status: str = None) -> List[Dict[str, Any]]:
        """List plans, optionally filtered by status"""
        plans = []
        
        # Check all plan directories
        for directory in ['active', 'completed', 'archive']:
            plan_dir = self.plans_dir / directory
            if not plan_dir.exists():
                continue
                
            for metadata_file in plan_dir.glob('*_metadata.json'):
                try:
                    metadata = json.loads(metadata_file.read_text())
                    if status is None or metadata.get('status') == status:
                        plans.append(metadata)
                except (json.JSONDecodeError, KeyError):
                    continue
        
        return sorted(plans, key=lambda x: x.get('created_at', ''), reverse=True)
    
    def get_plan(self, plan_id: str) -> Optional[Dict[str, Any]]:
        """Get a specific plan by ID"""
        plans = self.list_plans()
        for plan in plans:
            if plan.get('id') == plan_id:
                return plan
        return None


if __name__ == "__main__":
    # Test the plan manager
    print("🔍 Plan Manager Test")
    print("=" * 50)
    
    # Create test context
    test_context = {
        'current_dir': '/test/directory',
        'project_type': 'python',
        'rsc03_relation': 'development',
        'files_present': ['main.py', 'requirements.txt'],
        'git_info': {'status': 'clean', 'branch': 'main'}
    }
    
    # Test plan generation
    plan_manager = PlanManager()
    test_request = "build a web application with user authentication"
    
    print(f"📝 Generating plan for: {test_request}")
    plan_content = plan_manager.generate_plan(test_request, test_context)
    
    print("\n📋 Generated Plan:")
    print("=" * 50)
    print(plan_content)
    
    # Test plan saving
    plan_path = plan_manager.save_plan(plan_content, test_request)
    print(f"\n💾 Plan saved to: {plan_path}")
    
    # Test plan listing
    plans = plan_manager.list_plans()
    print(f"\n📚 Found {len(plans)} plans")
    for plan in plans:
        print(f"   - {plan['id']}: {plan['title']} ({plan['status']})")